### ISSUE TITLE
Error when calling a ticket

### ISSUE THREAD

**Issue by ernestoluciano** [mrf345/FQM#113] opened 2020-06-04 05:22 UTC
ERROR [sqlalchemy.pool.impl.NullPool] Exception during reset or similar
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 671, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 858, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 281473743909344 and this is thread id 281473798139920.
ERROR [sqlalchemy.pool.impl.NullPool] Exception closing connection <sqlite3.Connection object at 0xffffb48a7ab0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 671, in _finalize_fairy
    fairy._reset(pool)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 858, in _reset
    pool._dialect.do_rollback(self)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 502, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 281473743909344 and this is thread id 281473798139920.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/pool/base.py", line 261, in _close_connection
    self._dialect.do_close(connection)
  File "/usr/local/lib/python3.7/dist-packages/sqlalchemy/engine/default.py", line 508, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 281473743909344 and this is thread id 281473798139920.

**Comment by mrf345** [comment] 2020-06-04 22:37
Hi again @ernestoluciano , thanks for reporting #117 #114 #113

This is a duplicate of a known issue that i intend to resolve  in #105
I didn't prioritize it intentionally, since it's not a disruptive bug in my testing environment.
Did it cause any defects other than the error log for you ?

**Comment by ernestoluciano** [comment] 2020-06-04 22:42
it create a loop of GET and POST and disconnect the session saying that page doesn't exist

**Comment by mrf345** [comment] 2020-06-04 22:48
Interesting 🤔 well i will give reproducing it on Ubuntu a shot and prioritize a fix for it.
Thanks for taking the time!

**Comment by mrf345** [comment] 2020-06-05 19:23
Hi @ernestoluciano , i'm about to merge a PR https://github.com/mrf345/FQM/pull/124 that resolve the   issue.
Please let me know if the issue still persists.

**Closed** 2020-06-05 19:24 UTC
Labels: duplicate
