### ISSUE TITLE
No Sound if ticket is pull

### ISSUE THREAD

**Issue by rsuaghe** [mrf345/FQM#257] opened 2021-04-29 01:02 UTC
No Sound if ticket is pull. How to configure? Thank you.

**Comment by Denace** [comment] 2021-05-20 07:26
Ticket notification fails to play. From web console, the audio file cannot be decoded.
![image](https://user-images.githubusercontent.com/10940898/118937100-d57c8b80-b955-11eb-86dd-eb3685546714.png)

**Comment by mrf345** [comment] 2021-06-05 09:46
I guess you're using the executable version `.exe`, if so consider running the project from [the source-code](https://github.com/mrf345/FQM#--from-the-source) instead, since the issue is already resolved there, however I won't be able to create new executables anytime soon.

**Comment by cruzzed** [comment] 2021-06-23 14:16
Apparently, the deploy requirements file hasnt been updated with newer package bumps like gtts 2.2.4 and the instruction in Readme recommends to use deploy.txt to install requirements.

**Comment by mrf345** [comment] 2021-08-01 20:14
Good catch @cruzzed, the library we're using to generate the TTS is frequently updated, so we need to either keep updating with each release or unpin it (not a good idea given the many outdated dependencies we have) should be resolved with #266

**Closed** 2021-08-01 20:16 UTC
